export const GET_PARKINGSLOTS = "GET_PARKINGSLOTS";
export const DELETE_PARKINGSLOT = "DELETE_PARKINGSLOT";
export const ADD_PARKINGSLOT = "ADD_PARKINGSLOT";
export const GET_PARKINGSLOT = "GET_PARKINGSLOT";
export const UPDATE_PARKINGSLOT = "UPDATE_PARKINGSLOT";
export const FILTER_PARKINGSLOTS = "FILTER_PARKINGSLOTS";